### ISSUE TITLE
Website - Tax Management

### ISSUE THREAD

**Issue by Jignasha22** [FlowzPlatform/Sprint-User-Story-Board#10]
### Wiki
  - [Documentation](https://github.com/FlowzPlatform/Sprint-User-Story-Board/wiki/Website---Tax-Management-Flow)

**Comment by emp005169** [comment]
PUT ON HOLD DUE TO AMAZON AND WORKFLOW ASSIGNMENTS TO THE RESOURCE, NIKITA.

**Comment by nikitam747** [comment]
done tax management, also provided tax data to crm for invoices.

**Comment by Jignasha22** [comment]
Done and move to Staging.
