### ISSUE TITLE
Website - Quick Quote Page Funcationality

### ISSUE THREAD

**Issue by nnpatel** [FlowzPlatform/Sprint-User-Story-Board#106]
- User can add in QuickQuote List. 
- User can E-mail to anothe user for Quote.

### Prerequisite:
-Functionality must be working.

### User Story Description:
    As a <customer>, i need a <contact us component> so that i can easily drag and build contact us page.

### Acceptance Criteria:
1. Business Use case - 1
2. Business Use case - 2
 
###  Environment Applicable:

- Windows desktop OS
- Windows Server OS
- Linux

### Issue Summary:
----
### Prerequisite:
-Functionality must be working.

### Expected Result:
    1.Component should work
 
### Actual Result:
    1. Component is not working.
    
### Environment Details
    - Windows desktop OS
    - Windows Server OS
    - Linux

**Comment by Jignasha22** [comment]
Done and moved to staging.
