### ISSUE TITLE
Uploader-[feature]-Progress Bar display when import start

### ISSUE THREAD

**Issue by chiragob** [FlowzPlatform/Sprint-User-Story-Board#11]
### SUMMARY: customer can view his uploaded data progress on uploader portal

----
### Prerequisite:
- uploaded status update by JobQueue

### User Story Description:
    As a customer, i see progress of importing

### Acceptance Criteria:
1. based on importing data progress should be display

**Comment by emp005169** [comment]
what is the update ?

**Comment by chiragob** [comment]
Issue done : 
https://github.com/FlowzPlatform/uploader/commit/5a45a9cb9149656c7cdbe1f32fcc8d316befdc6f
