### ISSUE TITLE
SMTP configuration

### ISSUE THREAD

**Issue by HarshOB** [FlowzPlatform/Sprint-User-Story-Board#127]
set SMTP configuration for send mail proof process in FLOW

**Comment by KrishnaPG** [comment]
Please add the **screenshot** and **usage-instructions** before closing any feature request

**Comment by HarshOB** [comment]
I closed this issue because it was opened in workflow git repo. ([DUPLICATE](https://github.com/FlowzPlatform/workflow/issues/245))
