### ISSUE TITLE
website-builder - metalsmith publish jobqueue

### ISSUE THREAD

**Issue by mohit5540** [FlowzPlatform/Sprint-User-Story-Board#13]
- Publish process should run in background
- After publish show some notification

### SUMMARY:
---- check for grapes js updates
### Prerequisite:
-Functionality must be working.

### User Story Description:
    check for grapes js updates. check for backward compatibility

### Acceptance Criteria:
1. Business Use case - 1
2. Business Use case - 2

**Comment by gkumar9** [comment]
Completed and merged.

**Comment by gkumar9** [comment]
done and moved to staging
