### ISSUE TITLE
CRM - Dynamic Email Template 

### ISSUE THREAD

**Issue by npaulOB** [FlowzPlatform/Sprint-User-Story-Board#28]
### SUMMARY: Dynamic Invoice Template For each and every time one system email is fired.We need to determine if the data is dynamic or HTML also should be editable.
----
### Prerequisite:
-Functionality must be working.

### User Story Description:
    As a <customer>, i need a <contact us component> so that i can easily drag and build contact us page.

### Acceptance Criteria:
1. Business Use case - 1
2. Business Use case - 2

**Comment by mohit5540** [comment]
this is with reference to #23
