### ISSUE TITLE
website-builder - configure webpack

### ISSUE THREAD

**Issue by mohit5540** [FlowzPlatform/Sprint-User-Story-Board#34]
### SUMMARY:
---- add functionality to allow generating output files using webpack config 

### Prerequisite:
-Functionality must be working.

### User Story Description:
    add functionality to allow generating output files using webpack config 

### Acceptance Criteria:
1. Business Use case - 1
2. Business Use case - 2

**Comment by gkumar9** [comment]
-As per requirement webpack is to be invoked after successful metalsmith compilation.

Following are the steps involved:
- adding of a new file named webpack.config.js as a template
- at the time publish form the webpack.config.js with updated data
- after the adding all config of all page, then building output with web pack and deleting non-relevant data.

**Comment by KrishnaPG** [comment]
Reference: https://webpack.js.org/api/node/

**Comment by KrishnaPG** [comment]
````
function buildWebpack(skip) {
	return new Promise((resolve, reject) => {
		webpack(webpackConfig, function (err, stats) {
			if (err) reject(err);
			if(Array.isArray(webpackConfig)) // find build errors in array configuration
			{
				const erroredBuilds = stats.stats.filter(x => x.compilation.errors.length >0);
				if(erroredBuilds.length > 0)
				{
					const names = erroredBuilds.map(x => x.compilation.name);
					const errors = erroredBuilds.map(x => x.compilation.errors);
					const errorString = erroredBuilds.map(x => `\n[${x.compilation.name}]:\n${x.compilation.errors[0].substring(0, 250)}`).join('\n');
					reject(errorString);
				}
			}
			process.stdout.write(stats.toString({
				colors: true,
				modules: false,
				children: true,
				chunks: false,
				chunkModules: false
			}) + '\n');
			resolve(`[Done]: Webpack build [${(Array.isArray(webpackConfig) ? webpackConfig.map(config => config.name) : [webpackConfig.name]).join(', ')}]`);
		});
	});
}
````

**Comment by mohit5540** [comment]
ref : #132
