### ISSUE TITLE
Website - Marketing Tool Like Flyer and E-Catalog Management [Admin and Front]

### ISSUE THREAD

**Issue by Jignasha22** [FlowzPlatform/Sprint-User-Story-Board#38]
SUMMARY: Admin can manage to add ,edit and delete flyer and e-catalog.

----
### Prerequisite:
-Functionality must be working.

### User Story Description:
    As a <customer>, i need a <contact us component> so that i can easily drag and build contact us page.

### Acceptance Criteria:
1. Business Use case - 1
2. Business Use case - 2
 
###  Environment Applicable:

- Windows desktop OS
- Windows Server OS
- Linux

### Issue Summary:
----
### Prerequisite:
-Functionality must be working.

### Issue Reproduce Steps:
    1.Open URL.
    2. 
    
### Expected Result:
    1.Component should work
 
### Actual Result:
    1. Component is not working.
    
### Environment Details
    - Windows desktop OS
    - Windows Server OS
    - Linux

**Comment by Jignasha22** [comment]
Done.

**Comment by nnpatel** [comment]
Add new "Client Friendly PDF" option in builder dashboard(Marketing tools > Add flyer) and change flyer page html.

![flyer_page](https://user-images.githubusercontent.com/33539882/44850236-316cc680-ac7a-11e8-8833-98a717928867.png)
![new_pdf_option_in_flyer](https://user-images.githubusercontent.com/33539882/44850237-32055d00-ac7a-11e8-903e-6c39016550ad.png)
