### ISSUE TITLE
website-builder - vue component create

### ISSUE THREAD

**Issue by mohit5540** [FlowzPlatform/Sprint-User-Story-Board#44]
### SUMMARY:
---- able to create vue component
### Prerequisite:
-Functionality must be working.

### User Story Description:
    able to create vue component
    checkbox, dropdownbox, grid, listing, text, imagelinks, banner, radiobutton
----------------------------------------------------------------------------------------------------------------

### Acceptance Criteria:
1. Business Use case - 1
2. Business Use case - 2

**Comment by HarshOB** [comment]
Done and move to qa
