### ISSUE TITLE
website-builder - Image library functionality

### ISSUE THREAD

**Issue by emp005169** [FlowzPlatform/Sprint-User-Story-Board#51]
### SUMMARY:
---- User should be able to linc cloudinary account for images

### Prerequisite:
-Functionality must be working.

### User Story Description:
    - As a user, I should be able to show Cloudinary account images. 
    - User will provide cloudinary access keys in settings
    - There should be image upload feature, which allows to upload files on user's cloudinary account
    - Ref: vue dropzone

### Acceptance Criteria:
1. User has to provide Clodinary account access key. Feature will be disabled if its not provided.
2. Business Use case - 2

### Wiki
 - [Documentation](https://github.com/FlowzPlatform/Sprint-User-Story-Board/wiki/website-builder-:-Image-Library)

**Comment by Nikunj025** [comment]
Functionality is not Verified due to Web address , Camera and Instagram Section is not working.

**Comment by emp005169** [comment]
nikunj, do not move issues to development pipeline directly. you can keep them in opendefects.

**Comment by gkumar9** [comment]
Done and moved to staging.
