### ISSUE TITLE
Website - Creating Template For Wesite

### ISSUE THREAD

**Issue by mohit5540** [FlowzPlatform/Sprint-User-Story-Board#54]
### SUMMARY:
----
Index, Search, wishlist, compare, login, myaccount, editaccount, addressbooklist, addaddressbook, editaddressbook, changepassword and signup page templates are created.
### Prerequisite:
-Functionality must be working.

### User Story Description:
    As a <customer>, i need a <contact us component> so that i can easily drag and build contact us page.

### Acceptance Criteria:
1. Business Use case - 1
2. Business Use case - 2
 
###  Environment Applicable:

- Windows desktop OS
- Windows Server OS
- Linux

### Issue Summary:
----
### Prerequisite:
-Functionality must be working.

### Issue Reproduce Steps:
    1.Open URL.
    2. 
    
### Expected Result:
    1.Component should work
 
### Actual Result:
    1. Component is not working.
    
### Environment Details
    - Windows desktop OS
    - Windows Server OS
    - Linux

**Comment by emp005169** [comment]
khyati working on it.

**Comment by kkachhiya** [comment]
have to take care of "Save" content every time. if you bymistake click on other tab all addded content goes away if u forgot to SAVE.

**Comment by kkachhiya** [comment]
Everytime whole folder refresh if working as a sharing. we have to go back to page again click on parent-child-child.

**Comment by kkachhiya** [comment]
List of Pages:
1. index.html
2 | productCategoryView.html 
3 | ProductDetail.html 
4 | ProductCompare.html
5 | QuickQuote.html 
6 | WhishList.html 
7 | findDestributor.html 
8 | shoppingCart.html

List Of Partial Name With List Of partial

1 | Banner | default
2 | Footer | default
3 | GridLeftNev | default, CategoryFilter, Flag, PriceFilter, ColorFilter,  BrandFilter, RatingFilter, YearFilter
4 | Header | default, topHeader
5 | Menu | default
6 | ProductDetail | default, ProductDetailLeft, ProductDetailRight
7 | Sidebar | default

8 | featuredProduct | default,  newProduct
