### ISSUE TITLE
Merge Payment Gateway Schema

### ISSUE THREAD

**Issue by emp005169** [FlowzPlatform/Sprint-User-Story-Board#56]
### SUMMARY:
----
### Prerequisite:
-Functionality must be working.

### User Story Description:
    As a user, its schema should be same if it uses builder or crm. From both location backend (database) store must be same.

### Acceptance Criteria:
1. crm id should not be selected by user.
2. Business Use case - 2

**Comment by gkumar9** [comment]
Completed and merged.

**Comment by gkumar9** [comment]
Task completed and moved to staging.
