### ISSUE TITLE
webbuilder - website setting header text

### ISSUE THREAD

**Issue by emp005169** [FlowzPlatform/Sprint-User-Story-Board#61]
### Issue Summary:
----Website Setting headings rename as per business terms instead of technical terms along with how to use it.

### Issue Reproduce Steps:
    1. Go to website settings
    2. Check headings on right hand side.
    
### Expected Result:
    1. Heading should not be technical but understandable business terms for the end users using it. The details on how to use it to be mentioned as well.
 
### Actual Result:

![website settings](https://user-images.githubusercontent.com/34298251/38086446-02473290-3372-11e8-8492-840aac1a442f.png)

**Comment by gkumar9** [comment]
UI of projectsetting is changed and text are visible .Done
