### ISSUE TITLE
Uploader-[feature]- PDM data sync to ASI, SAGE

### ISSUE THREAD

**Issue by chiragob** [FlowzPlatform/Sprint-User-Story-Board#63]
### SUMMARY: Product data should be sync to SAGE and ASI
----
### Prerequisite:
- Product data must be available in PDM 

### User Story Description:
    As a supplier, i should be able to sync my product on SAGE and ASI platform so that distributer can easily use my product data.

### Acceptance Criteria:
1. data should be sync on both portal

###See [Wiki](https://github.com/FlowzPlatform/Sprint-User-Story-Board/wiki/%5BUploader%5D-:-Product-data-sync-to-Sage-and-ASI).

**Comment by emp005169** [comment]
sage xml ready however its api task is dependent on the credentials pending to fetch the feed live data.

**Comment by chiragob** [comment]
issue done :
https://github.com/FlowzPlatform/uploader/commit/a4f5729f197e1c1717e532d862fd96b4d38e0891
https://github.com/FlowzPlatform/uploader/commit/9efc13f1fe559a4e27b4fb6a85f0788ca5a9fad1
https://github.com/FlowzPlatform/uploader/commit/cbfa81522590064f7b13c329b54100cde23237ad
https://github.com/FlowzPlatform/uploader/commit/eb4f36ca0b71361cddac848c54694ad5fb43ff7e
