### ISSUE TITLE
Subscription - List of subscribers and plans selected with expiry date.

### ISSUE THREAD

**Issue by emp005169** [FlowzPlatform/Sprint-User-Story-Board#65]
### SUMMARY:
----UI admin to display list of subscribers and plans selected with expiry date.
### Prerequisite:
-Functionality must be working.

### User Story Description:
    As a flowz super admin, i need a UI admin to display list of subscribers and plans selected with expiry date and history log.

### Acceptance Criteria:
1. Business Use case - 1
2. Business Use case - 2

**Comment by chiragob** [comment]
issue done:
https://github.com/FlowzPlatform/subscription/commit/08d0fef951dfd066f1a54cdc1b04af04c81af024
