### ISSUE TITLE
Uploader - Promo Standard API Integration

### ISSUE THREAD

**Issue by Jignasha22** [FlowzPlatform/Sprint-User-Story-Board#66]
### SUMMARY:
----
### Prerequisite:
-Product data must be available in PDM.

### Acceptance Criteria:
1. Business Use case - 1
2. Business Use case - 2
 
###  Environment Applicable:

- Windows desktop OS
- Windows Server OS
- Linux

###See [Wiki](https://github.com/FlowzPlatform/Sprint-User-Story-Board/wiki/Promo-Standards--Intergration).

###See [PromoStandard Document](http://res.cloudinary.com/flowz/raw/upload/v1522761988/Promostand_fbvsps.docx)![PromoStandard Doc]

**Comment by nnpatel** [comment]
Example is added for each request for Promo Standard Service.

PFA
[promo_doc.zip](https://github.com/FlowzPlatform/Sprint-User-Story-Board/files/2114025/promo_doc.zip)

**Comment by Jignasha22** [comment]
Done.
