### ISSUE TITLE
webbuilder - delete page of a template website and save new page created, then publish error.

### ISSUE THREAD

**Issue by emp005169** [FlowzPlatform/Sprint-User-Story-Board#74]
### Issue Summary:
----
 Priyank | WebsiteBuilder | If I delete one page then try to add same page, It gives error.
 Javid | WebsiteBuilder | -socket issue: sometimes we are not able to save changes => on save it gives -> Failed! please try again.
 Javid | WebsiteBuilder | not giving successfully save notification

**Comment by gkumar9** [comment]
Cant reproduce .
