### ISSUE TITLE
PDM - LocationId, Imprint Id, ChargeId

### ISSUE THREAD

**Issue by Jignasha22** [FlowzPlatform/Sprint-User-Story-Board#79]
We need unique Location Id,Imprint Color Id,Charge Id to display in response of PromoStandared API
### Prerequisite:
-Functionality must be working.

### User Story Description:
    As a <customer>, i need a <contact us component> so that i can easily drag and build contact us page.

### Acceptance Criteria:
1. Business Use case - 1
2. Business Use case - 2
 
###  Environment Applicable:

- Windows desktop OS
- Windows Server OS
- Linux

### Issue Summary:
----
### Prerequisite:
-Functionality must be working.

### Issue Reproduce Steps:
    1.Open URL.
    2. 
    
### Expected Result:
    1.Component should work
 
### Actual Result:
    1. Component is not working.
    
### Environment Details
    - Windows desktop OS
    - Windows Server OS
    - Linux

**Comment by nnpatel** [comment]
Services are created for these three dependency, which will store the  related info in DB and use it as LocationId, Imprint Id, ChargeId(as per called service) in response.

**Comment by Jignasha22** [comment]
Done. moved to staging.
