### ISSUE TITLE
webbuilder - Flowzdigital website template work 

### ISSUE THREAD

**Issue by emp005169** [FlowzPlatform/Sprint-User-Story-Board#83]
### SUMMARY:
-----------------------------------------------------------------------------------------
### Prerequisite:
- Functionality must be working.
- Template should be provided.

### User Story Description:
    As a user, should be able to see flowzdigital website information @ flowzdigital.com built using our webbuilder platform.

**Comment by gkumar9** [comment]
Done and moved to staging
