### ISSUE TITLE
Project-settings file for all env (dev/qa/staging)

### ISSUE THREAD

**Issue by faizansaiyed** [FlowzPlatform/Sprint-User-Story-Board#86]
### Issue Summary:
----
### Prerequisite:
project-settings file for all env (dev/qa/staging)

### Issue Reproduce Steps:
    1.Import Template
    2. 
### Expected Result:
    1.Settings must contain proper URLs
 
### Actual Result:
    1. Settings does not contain proper URLs
    
### Environment Details
    - Windows desktop OS
    - Windows Server OS
    - Linux

**Comment by Jignasha22** [comment]
Done.
