### ISSUE TITLE
Project Configuration GET API takes too much time

### ISSUE THREAD

**Issue by faizansaiyed** [FlowzPlatform/Sprint-User-Story-Board#88]
### Issue Summary:
----
### Prerequisite:
-Project Configuration GET API takes too much time

### Expected Result:
    1. Less time in GET API
 
### Actual Result:
    1. Project Configuration GET API takes too much time
    
### Environment Details
    - Windows desktop OS
    - Windows Server OS
    - Linux

**Comment by emp005169** [comment]
this issue is part of optimization issue #34, #115
